project:
  type: website

website:
  title: "Brayan Cubides"
  repo-url: "https://github.com/bcubides-est/website.git"
  favicon: logo.png
  page-navigation: true

  navbar:
    left:
      - href: inicio.qmd
        text: Inicio
      - href: perfil.qmd
        text: Perfil
    right:
      - icon: download
        href: "javascript:window.print()"
    # --- CORRECCIÓN APLICADA AQUÍ ---
    # La propiedad `theme-toggle` debe estar DENTRO de la sección `navbar`.
    theme-toggle: true
    # ------------------------------

format:
  html:
    theme:
      light: light
      dark: cyborg
    toc: false
    css: styles.css